package ui;

public enum Type {
	BOOLEAN,NULL,NUMERIC,TEXT,BLOCK,COLUMB,CONCAT,CREATE,DATA,DELETE,DIV,DROP,GROUP_BY,
	INSERT,MINUS,MULT,NOT,NUMBER,OPERATOR,ORDER,ORDER_BY,PLUS,SELECT,SET,TABLE,TYPE,UMINUS,UPDATE,
	WHERE,PRIMARY_KEY;
}
